"""Local clipboard history. A fake pasteboard only. No Mac, no network, no iCloud."""
import json
import os
import stat
import tempfile
import unittest

import commands
from commands.clipboard_history import (
    CLIPBOARD_KEYS,
    CONCEALED_TYPES,
    ClipboardHistory,
    Snapshot,
    icloud_clipboard_path,
    load_clipboard,
    looks_like_secret,
    outbox_reply,
    password_manager_frontmost,
    poll_error_line,
    poll_once,
    preview_text,
    save_clipboard,
    secret_kind,
    types_are_concealed,
)
from commands.messages import LocalSpeech
from mini_bar import (
    clipboard_item_index,
    clipboard_menu,
    clipboard_menu_phrase,
    option_held,
    plus_item,
    plus_menu,
    walk_menu,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _func(source, name):
    start = source.index("def {0}".format(name))
    line_start = source.rfind("\n", 0, start) + 1
    indent = start - line_start
    marker = "\n" + (" " * indent) + "def "
    nxt = source.find(marker, start + 1)
    if nxt < 0:
        nxt = len(source)
    return source[start:nxt]


class TestFiltering(unittest.TestCase):
    def test_concealed_transient_and_autogenerated_types_are_skipped(self):
        for name in (
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ):
            self.assertIn(name, CONCEALED_TYPES)
            self.assertTrue(types_are_concealed(("public.utf8-plain-text", name)))
            history = ClipboardHistory()
            status = history.observe(Snapshot(1, "hello from a manager", types=(name,)))
            self.assertEqual(status, "concealed", name)
            self.assertEqual(history.texts(), [])

    def test_plain_text_without_those_types_is_stored(self):
        history = ClipboardHistory()
        status = history.observe(Snapshot(
            1, "grocery list", types=("public.utf8-plain-text",), frontmost="TextEdit"))
        self.assertEqual(status, "stored")
        self.assertEqual(history.texts(), ["grocery list"])

    def test_empty_whitespace_and_non_text_are_skipped(self):
        history = ClipboardHistory()
        self.assertEqual(history.observe(Snapshot(1, None)), "empty")
        self.assertEqual(history.observe(Snapshot(2, "   \n")), "empty")
        self.assertEqual(history.observe(Snapshot(3, b"\xff\xfe")), "empty")
        self.assertEqual(history.observe(Snapshot(4, 123456)), "empty")
        self.assertEqual(history.texts(), [])

    def test_standalone_otp_and_code_phrases_are_skipped(self):
        blocked = (
            "1234",
            "123456",
            "12345678",
            "  493021  ",
            "code is 123456",
            "Code: 847291",
            "your verification code is 493021",
            "OTP 123456",
            "the pin is 1234",
            "123456 is your code",
        )
        for text in blocked:
            self.assertEqual(secret_kind(text), "otp", text)
            history = ClipboardHistory()
            self.assertEqual(history.observe(Snapshot(1, text)), "secret", text)
            self.assertEqual(history.texts(), [], text)

    def test_ordinary_numbers_in_a_sentence_are_kept(self):
        kept = (
            "123",
            "123456789",
            "Meet in 2026",
            "room 12 at 3",
            "zip code is 90210",
            "area code is 909",
            "the barcode is 12345678",
        )
        for text in kept:
            self.assertIsNone(secret_kind(text), text)
            history = ClipboardHistory()
            self.assertEqual(history.observe(Snapshot(1, text)), "stored", text)
            self.assertEqual(history.texts(), [text.strip()], text)

    def test_key_prefixes_and_high_entropy_tokens_are_skipped(self):
        blocked = (
            "sk-abc123XYZdef456",
            "sk-ant-api03abcdefghij",
            "sk-proj-abc123456789xyz",
            "ghp_abcdefghijklmnopqrstuvwxyz",
            "github_pat_11AAAAAAA0bbbbbbbb",
            "crsr_live_abc123456789",
            "AKIAIOSFODNN7EXAMPLE",
            "prefix sk-abc123XYZdef456 in a note",
            "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0In0.dBjftJeZ4CVP",
            "aB3dE6gH9jK2mN5pQ8rT1vX4zA7cD0fG",
        )
        for text in blocked:
            self.assertTrue(looks_like_secret(text), text)
            history = ClipboardHistory()
            self.assertEqual(history.observe(Snapshot(1, text)), "secret", text)
            self.assertEqual(history.texts(), [], text)
        self.assertIsNone(secret_kind("I asked about the weather today"))
        self.assertIsNone(secret_kind("ApplicationSupportHeyJevClipboardHistory"))

    def test_a_secret_is_not_stored_just_because_it_is_long(self):
        key = "sk-" + ("aB3" * 20)
        history = ClipboardHistory(item_max=12)
        self.assertEqual(history.observe(Snapshot(1, key)), "secret")
        self.assertEqual(history.texts(), [])

    def test_password_manager_in_front_skips_even_a_normal_sentence(self):
        self.assertTrue(password_manager_frontmost("1Password"))
        self.assertTrue(password_manager_frontmost("1Password 8"))
        self.assertTrue(password_manager_frontmost("Bitwarden"))
        self.assertTrue(password_manager_frontmost("Passwords"))
        self.assertTrue(password_manager_frontmost("Google Password Manager"))
        self.assertTrue(password_manager_frontmost("Keychain Access"))
        self.assertTrue(password_manager_frontmost("Whatever", "com.apple.Passwords"))
        self.assertFalse(password_manager_frontmost("TextEdit"))
        self.assertFalse(password_manager_frontmost("Safari"))
        self.assertFalse(password_manager_frontmost("Notes"))
        history = ClipboardHistory()
        status = history.observe(Snapshot(1, "correct horse battery", frontmost="1Password"))
        self.assertEqual(status, "manager")
        self.assertEqual(history.texts(), [])
        self.assertEqual(
            history.observe(Snapshot(2, "correct horse battery", frontmost="Notes")),
            "stored",
        )

    def test_concealed_and_transient_password_copies_are_not_stored(self):
        """A concealed or transient pasteboard item is dropped, even when it looks like a login."""
        secret = "username ada@example.com password correct-horse"
        for name in (
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
        ):
            history = ClipboardHistory()
            status = history.observe(Snapshot(
                1,
                secret,
                types=("public.utf8-plain-text", name),
                frontmost="TextEdit",
            ))
            self.assertEqual(status, "concealed", name)
            self.assertEqual(history.texts(), [], name)
            self.assertNotIn(secret, " ".join(history.texts()))

    def test_copies_while_passwords_or_keychain_access_is_frontmost_are_skipped(self):
        """Apple Passwords and Keychain Access are skipped even with no concealed type."""
        secret = "ada@example.com correct-horse"
        cases = (
            {"frontmost": "Passwords", "bundle_id": None},
            {"frontmost": "Passwords", "bundle_id": "com.apple.Passwords"},
            {"frontmost": "Keychain Access", "bundle_id": None},
            {"frontmost": "Keychain Access", "bundle_id": "com.apple.keychainaccess"},
            {"frontmost": "Something", "bundle_id": "com.apple.Passwords"},
        )
        for number, case in enumerate(cases, start=1):
            history = ClipboardHistory()
            status = history.observe(Snapshot(
                number,
                secret,
                types=("public.utf8-plain-text",),
                frontmost=case["frontmost"],
                bundle_id=case["bundle_id"],
            ))
            self.assertEqual(status, "manager", case)
            self.assertEqual(history.texts(), [], case)
            self.assertNotIn("correct-horse", " ".join(history.texts()))
        history = ClipboardHistory()
        self.assertEqual(
            history.observe(Snapshot(
                1, "grocery list", types=("public.utf8-plain-text",), frontmost="Notes")),
            "stored",
        )
        self.assertEqual(history.texts(), ["grocery list"])


class TestHistory(unittest.TestCase):
    def test_change_count_dedupe_cap_and_length(self):
        history = ClipboardHistory(limit=3, item_max=10)
        self.assertEqual(history.observe(Snapshot(1, "alpha")), "stored")
        self.assertEqual(history.observe(Snapshot(1, "other")), "unchanged")
        self.assertEqual(history.texts(), ["alpha"])
        self.assertEqual(history.observe(Snapshot(2, "alpha")), "duplicate")
        self.assertEqual(history.texts(), ["alpha"])
        self.assertEqual(history.observe(Snapshot(3, "beta")), "stored")
        self.assertEqual(history.observe(Snapshot(4, "alpha")), "stored")
        self.assertEqual(history.texts(), ["alpha", "beta", "alpha"])
        long_text = "hello world"
        self.assertEqual(history.observe(Snapshot(5, long_text)), "stored")
        self.assertEqual(history.texts(), ["hello worl", "alpha", "beta"])

    def test_default_cap_is_25_and_the_oldest_is_evicted(self):
        self.assertEqual(commands.CLIPBOARD_HISTORY_LIMIT, 25)
        history = ClipboardHistory()
        for number in range(1, 27):
            self.assertEqual(history.observe(Snapshot(number, "item {0}".format(number))), "stored")
        texts = history.texts()
        self.assertEqual(len(texts), 25)
        self.assertEqual(texts[0], "item 26")
        self.assertEqual(texts[-1], "item 2")
        self.assertNotIn("item 1", texts)

    def test_default_item_length_is_capped(self):
        self.assertEqual(commands.CLIPBOARD_ITEM_MAX, 2000)
        history = ClipboardHistory()
        text = "a" * 2001
        self.assertEqual(history.observe(Snapshot(1, text)), "stored")
        self.assertEqual(history.texts(), ["a" * 2000])

    def test_pause_ignores_copies_and_resume_takes_the_next_change(self):
        history = ClipboardHistory()
        self.assertEqual(history.observe(Snapshot(1, "before")), "stored")
        self.assertIsInstance(commands.pause_clipboard_history(history), LocalSpeech)
        self.assertTrue(history.is_paused())
        self.assertEqual(history.observe(Snapshot(2, "while paused")), "paused")
        self.assertEqual(history.texts(), ["before"])
        self.assertEqual(history.observe(Snapshot(2, "while paused")), "unchanged")
        speech = commands.resume_clipboard_history(history)
        self.assertIsInstance(speech, LocalSpeech)
        self.assertIn("recording", speech.text)
        self.assertFalse(history.is_paused())
        self.assertEqual(history.observe(Snapshot(2, "while paused")), "unchanged")
        self.assertEqual(history.observe(Snapshot(3, "after")), "stored")
        self.assertEqual(history.texts(), ["after", "before"])

    def test_clear_drops_items_and_does_not_bring_the_same_copy_back(self):
        history = ClipboardHistory()
        history.observe(Snapshot(1, "gone soon"))
        speech = commands.clear_clipboard_history(history)
        self.assertIsInstance(speech, LocalSpeech)
        self.assertIn("cleared", speech.text.lower())
        self.assertEqual(history.texts(), [])
        self.assertEqual(history.observe(Snapshot(1, "gone soon")), "unchanged")
        self.assertEqual(history.texts(), [])

    def test_item_numbers_are_newest_first_and_out_of_range_is_refused(self):
        history = ClipboardHistory()
        history.observe(Snapshot(1, "older"))
        history.observe(Snapshot(2, "newer"))
        copied = []
        pasted = []
        speech = commands.copy_clipboard_from_text("copy item 1", writer=copied.append, history=history)
        self.assertIsInstance(speech, LocalSpeech)
        self.assertEqual(speech.text, "Copied item 1.")
        self.assertEqual(copied, ["newer"])
        self.assertNotIn("newer", speech.text)
        speech = commands.paste_clipboard_from_text(
            "paste item 2", writer=copied.append, paster=lambda: pasted.append("v"), history=history)
        self.assertEqual(speech.text, "Pasted item 2.")
        self.assertEqual(copied[-1], "older")
        self.assertEqual(pasted, ["v"])
        copied.clear()
        for phrase in ("copy item 3", "paste item 0", "copy item 99"):
            speech = commands.copy_clipboard_from_text(phrase, writer=copied.append, history=history)
            self.assertIn("no clipboard item", speech.text.lower(), phrase)
        self.assertEqual(copied, [])
        speech = commands.paste_clipboard_from_text(
            "paste item 8", writer=copied.append, paster=lambda: pasted.append("no"), history=history)
        self.assertIn("no clipboard item", speech.text.lower())
        self.assertEqual(pasted, ["v"])

        def boom(_text):
            raise OSError("pasteboard")

        speech = commands.paste_clipboard_from_text(
            "paste item 1", writer=lambda text: None, paster=boom, history=history)
        self.assertIn("couldn't paste", speech.text)
        self.assertNotIn("newer", speech.text)

    def test_spoken_history_is_a_short_local_preview(self):
        history = ClipboardHistory(preview_len=8, spoken_count=2)
        history.observe(Snapshot(1, "one"))
        history.observe(Snapshot(2, "two"))
        history.observe(Snapshot(3, "three is longer than the preview"))
        speech = commands.speak_clipboard_history(history)
        self.assertIsInstance(speech, LocalSpeech)
        self.assertEqual(speech.text, "Clipboard history. 1, three i\u2026. 2, two. 1 more.")
        self.assertNotIn("longer", speech.text)
        self.assertEqual(outbox_reply(speech), "")
        empty = commands.speak_clipboard_history(ClipboardHistory())
        self.assertEqual(empty.text, "Clipboard history is empty.")
        self.assertEqual(outbox_reply(empty), "")

    def test_poll_once_uses_the_reader_and_errors_do_not_include_the_text(self):
        history = ClipboardHistory()
        seen = []

        def reader():
            seen.append("read")
            return Snapshot(4, "from the fake board", frontmost="TextEdit")

        self.assertEqual(poll_once(history, reader), "stored")
        self.assertEqual(seen, ["read"])
        self.assertEqual(history.texts(), ["from the fake board"])

        class Boom(Exception):
            pass

        line = poll_error_line(Boom("sk-abc123XYZdef456 should not be logged"))
        self.assertEqual(line, "  clipboard: Boom")
        self.assertNotIn("sk-", line)

    def test_previews_truncate(self):
        self.assertEqual(preview_text("hello\nworld", 20), "hello world")
        self.assertEqual(preview_text("a" * 10, 8), "aaaaaaa\u2026")


class TestStorage(unittest.TestCase):
    def test_history_stays_in_memory_unless_someone_saves_it(self):
        history = ClipboardHistory()
        history.observe(Snapshot(1, "only in memory"))
        source = open(os.path.join(ROOT, "commands", "clipboard_history.py"), encoding="utf-8").read()
        observe = _func(source, "observe")
        self.assertNotIn("save_clipboard", observe)
        self.assertNotIn("BRIDGE_OUTBOX", source)
        self.assertNotIn("import socket", source)
        self.assertNotIn("socket.socket", source)
        self.assertNotIn("requests", source)
        self.assertNotIn("import AppKit", source.split("def read_general_pasteboard")[0])
        path = commands.CLIPBOARD_HISTORY_PATH
        self.assertTrue(path.endswith("Library/Application Support/Hey Jev/clipboard-history.json"))
        self.assertFalse(icloud_clipboard_path(path))

    def test_a_saved_file_is_owner_only_and_icloud_is_refused(self):
        history = ClipboardHistory()
        history.observe(Snapshot(1, "grocery list"))
        directory = tempfile.mkdtemp()
        self.addCleanup(lambda: _rmtree(directory))
        path = os.path.join(directory, "clipboard-history.json")
        save_clipboard(history, path)
        mode = stat.S_IMODE(os.stat(path).st_mode)
        self.assertEqual(mode, 0o600)
        loaded = ClipboardHistory()
        self.assertTrue(load_clipboard(loaded, path))
        self.assertEqual(loaded.texts(), ["grocery list"])
        # An existing looser mode is tightened on the next save.
        os.chmod(path, 0o644)
        save_clipboard(history, path)
        self.assertEqual(stat.S_IMODE(os.stat(path).st_mode), 0o600)

        icloud = os.path.expanduser(
            "~/Library/Mobile Documents/com~apple~CloudDocs/Jev/clipboard-history.json")
        self.assertTrue(icloud_clipboard_path(icloud))
        self.assertTrue(icloud_clipboard_path(commands.BRIDGE_OUTBOX))
        with self.assertRaises(ValueError):
            save_clipboard(history, icloud)
        with self.assertRaises(ValueError):
            load_clipboard(history, icloud)
        link = os.path.join(directory, "link.json")
        target_dir = os.path.join(directory, "Mobile Documents")
        os.makedirs(target_dir)
        target = os.path.join(target_dir, "clip.json")
        os.symlink(target, link)
        with self.assertRaises(ValueError):
            save_clipboard(history, link)
        self.assertFalse(os.path.exists(target))

    def test_loading_drops_a_secret_that_was_planted_in_the_file(self):
        directory = tempfile.mkdtemp()
        self.addCleanup(lambda: _rmtree(directory))
        path = os.path.join(directory, "clipboard-history.json")
        with open(path, "w", encoding="utf-8") as handle:
            json.dump({
                "v": 1,
                "items": ["keep me", "sk-abc123XYZdef456", "123456", 4, "also keep"],
            }, handle)
        os.chmod(path, 0o600)
        history = ClipboardHistory()
        self.assertTrue(load_clipboard(history, path))
        self.assertEqual(history.texts(), ["keep me", "also keep"])


class TestRouting(unittest.TestCase):
    def test_each_phrase_routes_and_stays_off_the_bridge_allowlist(self):
        phrases = (
            ("clipboard history", "clipboard_history"),
            ("my clipboard history", "clipboard_history"),
            ("show clipboard history", "clipboard_history"),
            ("show me my clipboard history", "clipboard_history"),
            ("please clipboard history", "clipboard_history"),
            ("what's on my clipboard history", "clipboard_history"),
            ("copy item 2", "clipboard_copy"),
            ("please copy clipboard item 2", "clipboard_copy"),
            ("copy item number 4", "clipboard_copy"),
            ("paste item 2", "clipboard_paste"),
            ("paste clipboard item 1", "clipboard_paste"),
            ("clear clipboard history", "clipboard_clear"),
            ("forget my clipboard history", "clipboard_clear"),
            ("pause clipboard history", "clipboard_pause"),
            ("pause the clipboard", "clipboard_pause"),
            ("resume clipboard history", "clipboard_resume"),
            ("resume the clipboard", "clipboard_resume"),
        )
        for phrase, key in phrases:
            self.assertEqual(commands.route_before_api(phrase), key, phrase)
            self.assertIn(key, CLIPBOARD_KEYS)
            self.assertNotIn(key, commands.BRIDGE_ALLOW, key)
            self.assertIsNone(commands.bridge_allowed(phrase), phrase)

    def test_new_patterns_do_not_steal_existing_phrases(self):
        existing = (
            ("pause", "media_pause"),
            ("pause the music", "media_pause"),
            ("resume", "media_play"),
            ("copy the screenshot", "capture_copy"),
            ("clear my shift Monday", "shift_clear"),
            ("what's playing", "media_now"),
            ("blue pill", "matrix_on"),
            ("what's on my calendar", "info_today_schedule"),
            ("check my messages from My Love", "info_messages"),
        )
        for phrase, key in existing:
            self.assertEqual(commands.route_before_api(phrase), key, phrase)
        for phrase in ("clipboard", "copy item", "paste item two", "clear my clipboard"):
            self.assertIsNone(commands.route_before_api(phrase), phrase)

    def test_handlers_return_local_speech_so_the_text_cannot_enter_the_outbox(self):
        history = ClipboardHistory()
        marker = "quarterly launch plan"
        history.observe(Snapshot(1, marker))
        results = (
            commands.speak_clipboard_history(history),
            commands.copy_clipboard_from_text("copy item 1", writer=lambda _text: None, history=history),
            commands.paste_clipboard_from_text(
                "paste item 1", writer=lambda _text: None, paster=lambda: None, history=history),
            commands.clear_clipboard_history(ClipboardHistory()),
            commands.pause_clipboard_history(ClipboardHistory()),
            commands.resume_clipboard_history(ClipboardHistory()),
        )
        sink = []
        for result in results:
            self.assertIsInstance(result, LocalSpeech)
            if not isinstance(result, LocalSpeech):
                sink.append(result)
            self.assertEqual(outbox_reply(result), "")
        self.assertEqual(sink, [])
        spoken = commands.speak_clipboard_history(history)
        self.assertIn("quarterly", spoken.text)
        self.assertNotIn(marker, outbox_reply(spoken))


class TestMenus(unittest.TestCase):
    def test_the_pill_submenu_lists_previews_and_does_not_queue_the_text(self):
        full = "quarterly launch plan that is longer than a menu preview should be"
        menu = plus_menu(clipboard_entries=((1, full), (2, "milk")))
        item = plus_item("clipboard_item_1", menu)
        self.assertEqual(item["kind"], "clipboard_item")
        self.assertEqual(item["phrase"], "")
        self.assertEqual(item["index"], 1)
        self.assertNotIn(full, item["title"])
        self.assertTrue(item["title"].startswith("1. "))
        self.assertIn("milk", plus_item("clipboard_item_2", menu)["title"])
        self.assertIsNone(clipboard_menu_phrase("clipboard_item_1"))
        self.assertEqual(clipboard_item_index("clipboard_item_2"), 2)
        self.assertIsNone(clipboard_item_index("clipboard_item_0"))
        self.assertIsNone(clipboard_item_index("clipboard_show"))
        self.assertEqual(clipboard_menu_phrase("clipboard_show"), "clipboard history")
        self.assertEqual(clipboard_menu_phrase("clipboard_clear"), "clear clipboard history")
        self.assertEqual(clipboard_menu_phrase("clipboard_pause"), "pause clipboard history")
        self.assertEqual(clipboard_menu_phrase("clipboard_resume"), "resume clipboard history")
        paused = clipboard_menu((), paused=True)
        ids = [row.get("id") for row in paused["items"]]
        self.assertIn("clipboard_resume", ids)
        self.assertNotIn("clipboard_pause", ids)
        self.assertEqual(paused["title"], "Clipboard History")
        self.assertTrue(option_held(1 << 19, 1 << 19))
        self.assertFalse(option_held(0, 1 << 19))
        self.assertFalse(option_held("nope", 1 << 19))
        for row in walk_menu(menu):
            if row["kind"] == "clipboard_item":
                self.assertEqual(row["phrase"], "")
                self.assertNotEqual(row["kind"], "text")

    def test_the_window_wires_the_pill_and_the_menu_bar_without_logging_the_text(self):
        ui = open(os.path.join(ROOT, "assistant_ui.py"), encoding="utf-8").read()
        siri = open(os.path.join(ROOT, "siri.py"), encoding="utf-8").read()
        menu = _func(ui, "miniPlus_")
        self.assertIn("clipboard_menu_entries", menu)
        self.assertIn("clipboard_entries=", menu)
        self.assertIn("plus_menu(recording=", menu)
        click = _func(ui, "miniPlusItem_")
        self.assertIn("clipboard_item_index", click)
        self.assertIn("clipboard_menu_phrase", click)
        self.assertNotIn('spec.get("title")', click)
        activate = _func(ui, "_activate_clipboard_from_menu")
        self.assertIn("_clipboard_status_line", activate)
        self.assertNotIn(".text", activate)
        build = _func(ui, "build_menu")
        self.assertIn("Clipboard History", build)
        self.assertIn("menuNeedsUpdate_", ui)
        self.assertIn("clipboardMenuItem:", ui)
        self.assertIn("setRepresentedObject_", _func(ui, "_refill"))
        self.assertIn("start_clipboard_thread()", siri)
        self.assertIn('"clipboard_history"', siri)
        run_local = _func(siri, "_run_local")
        self.assertIn("LocalSpeech", run_local)
        self.assertIn("commands.CLIPBOARD_KEYS", run_local)
        self.assertIn("type(exc).__name__ if private else exc", run_local)


def _rmtree(path):
    for root, dirs, files in os.walk(path, topdown=False):
        for name in files:
            os.remove(os.path.join(root, name))
        for name in dirs:
            os.rmdir(os.path.join(root, name))
    os.rmdir(path)


if __name__ == "__main__":
    unittest.main()
