"""Local voice commands: apps, calendar, weather, notes, and the iPhone bridge.

Names are parsed from the transcript here, the same way timers parse a duration.
decide() in siri.py calls route_before_api() before any TypeSafe or LLM call.

Nothing in this module listens on a socket. The iPhone bridge only polls an
iCloud Drive folder. Password lookup only opens the Passwords app and writes
a site name into its search field. It is not on the bridge allowlist.
The morning brief memo is a local file played with afplay
and is not on the bridge allowlist. App launches, site URLs, and shortcut runs
go through argument lists, never a shell string. A shortcut runs only when the Jev folder
can be verified; `shortcuts list --folder-name` alone is not proof, because a
missing folder makes that command print every shortcut. Message text is
returned as LocalSpeech so the caller can speak it with the macOS say command
and must not send it to Fish or any API. Bank and portal pages are opened in
Chrome only. This module never fetches them and never moves money."""
import subprocess  # re-exported so tests can patch commands.subprocess.run

from .config import (
    FUZZY_CUTOFF,
    APP_FUZZY_CUTOFF,
    APP_INDEX_TTL,
    CONFIRM_SECONDS,
    SHORTCUT_FOLDER,
    SHORTCUT_CACHE_SECONDS,
    SHIFT_TITLE_PATTERNS,
    SHIFT_HORIZON_DAYS,
    SCHOOL_HORIZON_DAYS,
    BILL_HORIZON_DAYS,
    DEFAULT_APPLE_PAY_ANCHOR,
    SHIFT_OVERRIDE_PATH,
    HOME_ADDRESS,
    BREA_STORE_ADDRESS,
    LEAVE_BUFFER_MINUTES,
    LEAVE_TYPICAL_DRIVE_MINUTES,
    LEAVE_REMINDERS_ENABLED,
    LEAVE_PREWARN_MINUTES,
    LEAVE_POLL_FAR_SECONDS,
    LEAVE_POLL_NEAR_SECONDS,
    LEAVE_POLL_CLOSE_SECONDS,
    LEAVE_NEAR_MINUTES,
    LEAVE_CLOSE_MINUTES,
    LEAVE_NUDGE_STATE_PATH,
    SWEEP_AMOUNT,
    SWEEP_ACCOUNT_LABEL,
    IHSS_PAYDAY_REMINDER,
    SWEEP_SPOKEN_PATH,
    ZOE_MODE_PATH,
    VOICE_MODE_PATH,
    BRIEF_MEMO_DIR,
    BRIEF_MEMO_TIME,
    BRIEF_MEMO_ENABLED,
    BRIEF_MEMO_RETRIES,
    BRIEF_MEMO_WINDOW_MINUTES,
    BRIEF_MEMO_POLL_SECONDS,
    BRIEF_MEMO_STATE_PATH,
    PRINCESS_SHORTCUT,
    PRINCESS_ACADEMY_URL,
    SHOPIFY_ORDERS_URL,
    BRIGHTNESS_UP_CODE,
    BRIGHTNESS_DOWN_CODE,
    SHOW_DESKTOP_CODE,
    VOLUME_WORDS,
    ZOE_EVENT_RE,
    MY_LOVE_HANDLES,
    MESSAGES_DB,
    JEV_DOCS,
    VIDEOS_FOLDER,
    CLIPBOARD_HISTORY_LIMIT,
    CLIPBOARD_ITEM_MAX,
    CLIPBOARD_PREVIEW_LEN,
    CLIPBOARD_SPOKEN_COUNT,
    CLIPBOARD_POLL_SECONDS,
    CLIPBOARD_HISTORY_PATH,
    NOTES_PATH,
    DUE_PATH,
    IHSS_PATH,
    MONEY_PATH,
    DUE_HORIZON_DAYS,
    REMINDERS_LIST,
    UPLAND_LAT,
    UPLAND_LON,
    WEATHER_TIMEOUT,
    FOCUS_ON_NAME,
    FOCUS_OFF_NAME,
    FOCUS_DEFAULT_SECONDS,
    CASE_STATUS_URL,
    GMAIL_TOKEN_ACCOUNT,
    BRIDGE_INBOX,
    BRIDGE_OUTBOX,
    BRIDGE_SECRET_ACCOUNT,
    BRIDGE_MAX_AGE,
    BRIDGE_MAX_CMD,
    BRIDGE_POLL_SECONDS,
    OUTBOX_TTL_SECONDS,
    NONCE_LOG,
    NONCE_LIMIT,
    NONCE_RE,
    BRIDGE_ALLOW,
    KNOWN_APPS,
    APP_NICKNAMES,
    SITE_CONFIG,
    FOLDER_PATHS,
    APP_DIRS,
    FINDER_PATH,
    PROTECTED_IDS,
    PROTECTED_NAMES,
    CONFIRM,
    YES_RE,
    NO_RE,
    QUIT_ALL_RE,
    QUIT_ALL_ONLY_RE,
    _OPEN_VERBS,
    _QUIT_VERBS,
    _HIDE_VERBS,
    _FOCUS_VERBS,
    JOINER_RE,
    _PLEASE,
    _TAIL,
    _PLAY,
    STRICT_PATTERNS,
    _NOTE_CMD_RE,
    _IHSS_CMD_RE,
    _BARE_RUN_RE,
    LOCAL_PATTERNS,
    HELP_TEXT,
    SCHOOL_RE,
    BILL_RE,
)

from .textutil import (
    _clean,
    _norm,
    _ordinal,
    _clock,
    _in_how_long,
    _day_phrase,
    _join_names,
    _month_day,
    _spoken_span,
    _hours_phrase,
    _until_day,
    _hours_minutes,
    _weekday_month,
)

from .shell import (
    _run,
)

from .confirm import (
    _PENDING,
    confirmation_pending,
    clear_confirmation,
    arm_confirmation,
    refresh_confirmation,
    confirmation_status,
    take_confirmation,
    isolate_confirmations,
    is_quit_all,
    quit_all_is_compound,
    is_private_message_request,
)

from .apps import (
    _index_cache,
    app_alias_map,
    site_index,
    _drop_my,
    _lookup_app,
    known_app_name,
    resolve_site,
    resolve_folder,
    music_target,
    app_index,
    _display_name,
    resolve_app,
    parse_app_name,
    _appkit,
    running_regular_apps,
    _own_pids,
    _is_self,
    is_protected,
    _running_match,
    _is_running,
    launch_app,
    open_any_app,
    normalize_app_phrase,
    unclear_app_guess,
    UNCLEAR_APP,
    quit_any_app,
    hide_any_app,
    focus_any_app,
    quit_all_apps,
    speak_open_apps,
    app_is_installed,
)

from .time_date import (
    speak_time,
    speak_date,
)

from .calendar_shift import (
    _store,
    _calendar_granted,
    _CAL_MISSING,
    _CAL_DENIED,
    _CAL_FAILED,
    _import_eventkit,
    _event_store,
    _wait_for,
    _request_full_access,
    ensure_calendar_access,
    _nsdate,
    _stamp,
    _title,
    _all_day,
    _cancelled,
    _events_between,
    _calendar_problem,
    _upcoming,
    speak_next_event,
    speak_today_schedule,
    is_shift_title,
    speak_next_shift,
    _calendar_name,
    speak_zoe_tomorrow,
    _plain_event,
    _load_plain_events,
    weekend_bounds,
    _covers_day,
    describe_work_weekend,
    describe_shift_length,
    speak_working_weekend,
    speak_shift_length,
    _plain_shifts_from_calendar,
    _speak_plain_shift,
)

from .shift_override import (
    clear_shift_override,
    events_with_overrides,
    load_shift_overrides,
    merge_shift_overrides,
    override_events,
    parse_shift_clear,
    parse_shift_set,
    resolve_shift_day,
    set_shift_override,
)

from .travel import (
    expected_travel_seconds,
)

from .leave import (
    describe_leave,
    speak_eta_to_work,
    speak_leave_time,
)

from .leave_nudge import (
    deliver_due_nudges,
    due_leave_nudges,
    hold_leave_nudges,
    leave_poll_seconds,
    leave_reminders_enabled,
    mac_output_muted,
    post_leave_notification,
    record_leave_nudge,
    run_leave_nudge_once,
    set_leave_quiet_probe,
    set_leave_reminders,
    start_leave_nudge_thread,
)

from .weather import (
    _WMO,
    _WEATHER_FAIL,
    _weather_phrase,
    speak_weather,
    gmail_brief_line,
    _gmail_stub_noted,
)

from .notes_due import (
    take_note,
    _dated_lines,
    _read_due_lines,
    speak_due,
)

from .reminders import (
    REMINDERS_AUTOMATION,
    REMINDERS_DENIED,
    REMINDERS_FAIL,
    REMINDERS_NO_DEFAULT,
    REMINDERS_UNCLEAR,
    add_reminder,
    confirmation_line,
    parse_reminder_request,
)

from .money import (
    _semi_period,
    _parse_ihss,
    _period_total,
    log_ihss,
    brea_from_due,
    speak_brea_start,
    _filtered_due,
    _speak_item_list,
    speak_school_due,
    speak_rent,
    speak_bills,
    next_biweekly,
    _month_end,
    next_semi_payday,
    load_pay_schedule,
    speak_payday,
    is_apple_payday,
    is_ihss_payday,
    is_timesheet_day,
    sweep_reminder_line,
    speak_payday_check,
    claim_daily_sweep,
    speak_ihss_period,
    remind_timesheet,
)

from .messages import (
    LocalSpeech,
    _FDA_MESSAGE,
    _is_fda_error,
    decode_attributed_body,
    _typedstream_string,
    _message_body,
    _clip_speech,
    _probe_messages_db,
    _open_messages_db,
    speak_my_love_messages,
)

from .system import (
    speak_help,
    _https_url,
    _open_in_chrome,
    open_site_from_text,
    open_folder_from_text,
    open_videos_folder,
    videos_folder_path,
    OPENING_VIDEOS,
    MISSING_VIDEOS,
    change_brightness,
    show_desktop,
    speak_battery,
    take_screenshot,
    empty_trash,
    continue_chatgpt,
    open_case_status,
)

from .captures import (
    CAPTURE_ROUTE_KEYS,
    CaptureBook,
    ask_jev_from_text,
    ask_from_text,
    ask_plan,
    ask_subject,
    capture_name,
    captures_folder,
    clipboard_script,
    delete_script,
    email_script,
    find_ffmpeg,
    imessage_plan,
    is_recording,
    note_question,
    open_captures_folder,
    notes_script,
    recording_clock,
    recording_command,
    recording_status,
    run_capture_menu,
    screenshot_command,
    share_from_text,
    start_screen_recording,
    stop_screen_recording,
    take_screenshot as capture_screenshot,
)

from .video import (
    AVCONVERT_PRESETS,
    FFMPEG_CANDIDATES,
    MISSING_FFMPEG,
    VIDEO_ROUTE_KEYS,
    avconvert_command,
    choose_video,
    ffmpeg_command,
    find_avconvert,
    format_clock,
    is_video_extension,
    locate_tool,
    notification_command,
    output_path,
    parse_clock,
    spawn_background,
    trim_bounds,
    video_from_text,
)

from .media import (
    play_on_youtube,
    parse_volume_level,
    set_mac_volume,
    change_mac_volume,
    mute_mac_volume,
)

from .access import (
    silence_notifications,
    speak_screen,
    stop_reading,
    read_selection,
    set_voiceover,
    press_zoom,
    set_access_feature,
    accessibility_status,
)

from .matrix import (
    start_matrix,
    stop_matrix,
)

from .passwords import (
    DICTATED_RE,
    LOOKUP_RE,
    PASSWORD_KEYS,
    PASSWORD_LOOKUP,
    PASSWORDS_BUNDLE,
    SEARCH_SCRIPT,
    is_password_lookup,
    lookup_password,
    parse_password_query,
)

from .clipboard_history import (
    CLIPBOARD,
    CLIPBOARD_KEYS,
    activate_clipboard_index,
    clear_clipboard_history,
    clipboard_is_paused,
    clipboard_menu_entries,
    copy_clipboard_from_text,
    icloud_clipboard_path,
    load_clipboard,
    outbox_reply,
    paste_clipboard_from_text,
    pause_clipboard_history,
    poll_once,
    resume_clipboard_history,
    save_clipboard,
    speak_clipboard_history,
    start_clipboard_thread,
)

from .shortcuts import (
    _UUID_RE,
    _shortcut_cache,
    run_jev_folder_shortcut,
    begin_focus,
    finish_focus,
    open_princess_academy,
    parse_shortcut_name,
    spoken_shortcut_from,
    clear_shortcut_cache,
    _shortcuts_output,
    _parse_id_line,
    parse_shortcut_ids,
    parse_folder_rows,
    find_jev_folder,
    catalog_from_listings,
    _load_shortcut_catalog,
    jev_shortcut_catalog,
    list_jev_shortcuts,
    resolve_shortcut,
    _ident_for_name,
    _run_catalog_shortcut,
    run_named_shortcut,
)

from .routing import (
    route_before_api,
    preview_action,
    route_open_phrase,
    route_named_app,
    bare_run_matches_folder,
)

from .fish_voice import (
    DEFAULT_CUE,
    DRAMA_MODEL,
    FISH_MODEL,
    FISH_TTS_TIMEOUT,
    FISH_TTS_URL,
    Speech,
    cache_token,
    claim_drama_plan_notice,
    dramatic_voice_enabled,
    play_fish_reply,
    set_voice_mode_path,
    speech_request,
    strip_fish_cues,
    synthesize_speech,
    use_dramatic_voice,
    use_normal_voice,
    which_voice,
)

from .zoe_mode import (
    JOKES,
    KID_REFUSAL,
    ZOE_ALLOW,
    ZOE_ALREADY_OFF,
    ZOE_ALREADY_ON,
    ZOE_BLOCKED,
    ZOE_EXIT_PHRASE,
    ZOE_EXIT_PROMPT,
    ZOE_EXIT_SECONDS,
    ZOE_OFF_LINE,
    ZOE_ON_LINE,
    ZOE_STAY_LINE,
    ask_leave_zoe_mode,
    clear_zoe_exit,
    enter_zoe_mode,
    leave_zoe_mode,
    menu_toggle_plan,
    set_zoe_mode_path,
    tell_zoe_joke,
    zoe_allows,
    zoe_claims,
    zoe_exit_pending,
    zoe_friendly,
    zoe_guard,
    zoe_mode_active,
    zoe_pill_label,
    zoe_plain,
)

from .bridge import (
    _bridge_thread,
    _bridge_lock,
    _bridge_secret_warned,
    bridge_allowed,
    _canonical_ts,
    _bridge_secret,
    _expected_sig,
    _load_nonces,
    _remember_nonce,
    _nonce_used,
    _write_outbox,
    _delete_inbox,
    _process_bridge_file,
    poll_bridge,
    start_bridge_thread,
)

from .brief import (
    speak_today,
    _count_today_events,
    speak_brief,
)

from .stt import (
    NO_SPEECH_MAX,
    WHISPER_HOTWORDS,
    is_hotword_echo,
    transcript_from_segments,
    whisper_transcribe_kwargs,
)

from .dictation_engine import (
    DICTATION_ENGINE_KEYS,
    FALLBACK_FAILED,
    FALLBACK_OPENAI,
    FALLBACK_WHISPER,
    OPENAI_MODEL,
    OPENROUTER_TRANSCRIPTIONS_URL,
    SCRIBE_MODEL,
    SCRIBE_USD_PER_SECOND,
    dictation_engine,
    set_dictation_engine,
    set_dictation_engine_path,
)

from .brief_memo import (
    BriefPlayback,
    EMPTY_FOLDER_LINE,
    MISSING_FOLDER_LINE,
    NOT_READY_LINE,
    afplay_command,
    brief_memo_settings,
    list_memos,
    play_memo_file,
    request_brief,
    run_scheduled_brief,
    start_brief_memo_thread,
    stop_brief,
)
