"""Recent plain-text clipboard items. Mac only, and only on this Mac.

The poller watches NSPasteboard.changeCount. It stores plain text in memory.
Secrets, one-time codes, concealed pasteboard types, and copies made while a
password manager is in front are dropped. Nothing here is sent to an API, an
LLM, the iPhone bridge, or iCloud. Replies are LocalSpeech so the Mac `say`
command speaks them and the bridge outbox never receives the text.

A file is written only when save_clipboard is called. That path has to stay
out of iCloud, and the file mode is 0600. The running app does not call it.
"""
from math import log
import json
import os
import re
import threading
import time

from .config import (
    CLIPBOARD_HISTORY_LIMIT,
    CLIPBOARD_HISTORY_PATH,
    CLIPBOARD_ITEM_MAX,
    CLIPBOARD_POLL_SECONDS,
    CLIPBOARD_PREVIEW_LEN,
    CLIPBOARD_SPOKEN_COUNT,
)
from .messages import LocalSpeech

# Password managers mark concealed or generated clipboard data with these types.
CONCEALED_TYPES = frozenset({
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
})

CLIPBOARD_KEYS = frozenset({
    "clipboard_history",
    "clipboard_copy",
    "clipboard_paste",
    "clipboard_clear",
    "clipboard_pause",
    "clipboard_resume",
})

# Spoken or localized app names. Matched as the whole name, or the name plus a version.
_PASSWORD_NAMES = (
    "1password",
    "bitwarden",
    "lastpass",
    "dashlane",
    "keepassxc",
    "keepass",
    "enpass",
    "nordpass",
    "roboform",
    "keeper password manager",
    "keeper",
    "proton pass",
    "google password manager",
    "strongbox",
    "macpass",
    "buttercup",
    "passwords",
    "keychain access",
)

# Bundle ids. Prefixes end with a dot so they do not match an unrelated app.
_PASSWORD_BUNDLES = (
    "com.1password.",
    "com.agilebits.onepassword",
    "com.bitwarden.desktop",
    "com.lastpass.",
    "com.dashlane.",
    "org.keepassxc.",
    "com.apple.Passwords",
    "com.apple.keychainaccess",
)

_OTP_STANDALONE = re.compile(r"^\d{4,8}$")
_OTP_PHRASE = re.compile(
    r"\b(?:"
    r"(?:verification|security|login|auth(?:entication)?|one[- ]time|two[- ]factor|2fa)\s+code"
    r"|one[- ]time\s+password"
    r"|passcode"
    r"|otp"
    r"|pin"
    r"|(?<!zip )(?<!area )(?<!error )(?<!status )(?<!country )(?<!bar )(?<!dress )code"
    r")\b\s*(?:is|:)?\s*[:\-]?\s*\d{4,8}\b",
    re.I,
)
_OTP_TRAILING = re.compile(
    r"\b\d{4,8}\s+is\s+your\s+(?:code|otp|pin|passcode)\b",
    re.I,
)
_KEY_PREFIX = re.compile(
    r"(?:^|[^A-Za-z0-9])(?:"
    r"sk-(?:ant-|proj-)?[A-Za-z0-9_\-]{8,}"
    r"|ghp_[A-Za-z0-9]{8,}"
    r"|github_pat_[A-Za-z0-9_]{8,}"
    r"|crsr_[A-Za-z0-9_\-]{8,}"
    r"|AKIA[A-Z0-9]{16}"
    r")"
)
_JWT = re.compile(r"\beyJ[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}\b")
_TOKEN = re.compile(r"^[A-Za-z0-9+/=_\-]{32,}$")
_ITEM_RE = re.compile(r"\bitem\s+(?:number\s+)?(\d+)\b", re.I)

_thread = None
_thread_lock = threading.Lock()


class Snapshot(object):
    """One look at the general pasteboard. Tests build these. The Mac reader does too."""

    def __init__(self, change_count, text=None, types=(), frontmost=None, bundle_id=None):
        self.change_count = change_count
        self.text = text
        self.types = types
        self.frontmost = frontmost
        self.bundle_id = bundle_id


def _norm_app(name):
    return " ".join(str(name or "").lower().split())


def types_are_concealed(types):
    """True when the pasteboard carries a password-manager concealed type."""
    if not isinstance(types, (list, tuple)):
        return False
    for item in types:
        if str(item) in CONCEALED_TYPES:
            return True
    return False


def password_manager_frontmost(name, bundle_id=None):
    """Best-effort. A known password manager in front means the copy is skipped."""
    bundle = str(bundle_id or "")
    for prefix in _PASSWORD_BUNDLES:
        if bundle == prefix or bundle.startswith(prefix):
            return True
    cleaned = _norm_app(name)
    if not cleaned:
        return False
    for app in _PASSWORD_NAMES:
        if cleaned == app or cleaned.startswith(app + " "):
            return True
    return False


def _shannon(text):
    counts = {}
    for ch in text:
        counts[ch] = counts.get(ch, 0) + 1
    length = float(len(text))
    total = 0.0
    for count in counts.values():
        probability = count / length
        total -= probability * (log(probability) / log(2.0))
    return total


def _high_entropy_token(text):
    """One long token that looks like a key, not a sentence."""
    for part in str(text or "").split():
        if not _TOKEN.match(part):
            continue
        if len(part) < 32:
            continue
        has_letter = re.search(r"[A-Za-z]", part) is not None
        has_digit = re.search(r"\d", part) is not None
        if not (has_letter and has_digit):
            continue
        if len(set(part)) < 8:
            continue
        if _shannon(part) >= 4.0:
            return True
    return False


def secret_kind(text):
    """'otp', 'key', or 'entropy' when the text must not be stored. Else None."""
    raw = str(text or "").strip()
    if not raw:
        return None
    if _OTP_STANDALONE.match(raw) or _OTP_PHRASE.search(raw) or _OTP_TRAILING.search(raw):
        return "otp"
    if _KEY_PREFIX.search(raw) or _JWT.search(raw):
        return "key"
    if _high_entropy_token(raw):
        return "entropy"
    return None


def looks_like_secret(text):
    return secret_kind(text) is not None


def plain_text(text):
    """A str, or empty when the pasteboard has no plain text."""
    if text is None:
        return ""
    if isinstance(text, bytes):
        try:
            text = text.decode("utf-8")
        except UnicodeDecodeError:
            return ""
    if not isinstance(text, str):
        return ""
    return text


def preview_text(text, limit=None):
    """One short line for a menu title or a spoken preview. Newlines become spaces."""
    if limit is None:
        limit = CLIPBOARD_PREVIEW_LEN
    flat = " ".join(str(text or "").split())
    limit = int(limit)
    if limit < 1 or len(flat) <= limit:
        return flat
    if limit == 1:
        return "\u2026"
    return flat[:limit - 1].rstrip() + "\u2026"


def parse_item_index(text):
    """1-based item number from 'copy item 2' or 'paste item number 3'. Else None."""
    match = _ITEM_RE.search(plain_text(text))
    if not match:
        return None
    return int(match.group(1))


def icloud_clipboard_path(path):
    """True when a save would land in iCloud Drive."""
    expanded = os.path.abspath(os.path.expanduser(str(path or "")))
    try:
        real = os.path.realpath(expanded)
    except OSError:
        real = expanded
    for candidate in (expanded, real):
        lowered = candidate.replace("\\", "/").lower()
        if "mobile documents" in lowered or "com~apple~clouddocs" in lowered:
            return True
    return False


def poll_error_line(exc):
    """A log line that names the error type and never the clipboard text."""
    return "  clipboard: {0}".format(type(exc).__name__)


class ClipboardHistory(object):
    """Newest first. A lock covers the list, the pause flag, and the last change count."""

    def __init__(self, limit=None, item_max=None, preview_len=None, spoken_count=None):
        self.limit = CLIPBOARD_HISTORY_LIMIT if limit is None else int(limit)
        self.item_max = CLIPBOARD_ITEM_MAX if item_max is None else int(item_max)
        self.preview_len = CLIPBOARD_PREVIEW_LEN if preview_len is None else int(preview_len)
        self.spoken_count = CLIPBOARD_SPOKEN_COUNT if spoken_count is None else int(spoken_count)
        self.items = []
        self.paused = False
        self.last_change = None
        self._lock = threading.Lock()

    def observe(self, snapshot):
        """Record one pasteboard change. The return value is a status, never the text."""
        with self._lock:
            count = int(snapshot.change_count)
            if self.last_change is not None and count == self.last_change:
                return "unchanged"
            self.last_change = count
            if self.paused:
                return "paused"
            if types_are_concealed(getattr(snapshot, "types", ())):
                return "concealed"
            if password_manager_frontmost(
                getattr(snapshot, "frontmost", None),
                getattr(snapshot, "bundle_id", None),
            ):
                return "manager"
            text = plain_text(getattr(snapshot, "text", None)).strip()
            if not text:
                return "empty"
            if looks_like_secret(text):
                return "secret"
            if len(text) > self.item_max:
                text = text[:self.item_max]
            if self.items and self.items[0] == text:
                return "duplicate"
            self.items.insert(0, text)
            if len(self.items) > self.limit:
                del self.items[self.limit:]
            return "stored"

    def clear_items(self):
        with self._lock:
            self.items = []

    def set_paused(self, paused):
        with self._lock:
            self.paused = bool(paused)
            return self.paused

    def is_paused(self):
        with self._lock:
            return self.paused

    def texts(self):
        with self._lock:
            return list(self.items)

    def text_at(self, index):
        """1-based. Item 1 is the newest. None when the number is out of range."""
        try:
            number = int(index)
        except (TypeError, ValueError):
            return None
        with self._lock:
            if number < 1 or number > len(self.items):
                return None
            return self.items[number - 1]

    def spoken(self):
        with self._lock:
            items = list(self.items)
            paused = self.paused
            limit = self.preview_len
            count = self.spoken_count
        if not items:
            if paused:
                return "Clipboard history is paused, and it's empty."
            return "Clipboard history is empty."
        shown = items[:count]
        bits = []
        for index, text in enumerate(shown, 1):
            bits.append("{0}, {1}".format(index, preview_text(text, limit)))
        sentence = ". ".join(bits)
        head = "Clipboard history is paused. " if paused else "Clipboard history. "
        left = len(items) - len(shown)
        if left == 1:
            extra = " 1 more."
        elif left > 1:
            extra = " {0} more.".format(left)
        else:
            extra = ""
        return head + sentence + "." + extra

    def menu_entries(self):
        """(index, preview) newest first. The preview is not the full item."""
        with self._lock:
            items = list(self.items)
            limit = self.preview_len
        entries = []
        for index, text in enumerate(items, 1):
            entries.append((index, preview_text(text, limit)))
        return entries

    def replace_items(self, items):
        """Used when loading a file. Secrets are dropped again. Newest stays first."""
        kept = []
        for text in items:
            if not isinstance(text, str):
                continue
            cleaned = text.strip()
            if not cleaned or looks_like_secret(cleaned):
                continue
            if len(cleaned) > self.item_max:
                cleaned = cleaned[:self.item_max]
            kept.append(cleaned)
            if len(kept) >= self.limit:
                break
        with self._lock:
            self.items = kept


CLIPBOARD = ClipboardHistory()


def speak_clipboard_history(history=None):
    history = CLIPBOARD if history is None else history
    return LocalSpeech(history.spoken())


def clear_clipboard_history(history=None):
    history = CLIPBOARD if history is None else history
    history.clear_items()
    return LocalSpeech("Clipboard history is cleared.")


def pause_clipboard_history(history=None):
    history = CLIPBOARD if history is None else history
    history.set_paused(True)
    return LocalSpeech("Clipboard history is paused.")


def resume_clipboard_history(history=None):
    history = CLIPBOARD if history is None else history
    history.set_paused(False)
    return LocalSpeech("Clipboard history is recording again.")


def clipboard_is_paused(history=None):
    history = CLIPBOARD if history is None else history
    return history.is_paused()


def clipboard_menu_entries(history=None):
    history = CLIPBOARD if history is None else history
    return history.menu_entries()


def _activate(history, index, paste, writer, paster):
    text = history.text_at(index)
    if text is None:
        try:
            number = int(index)
        except (TypeError, ValueError):
            number = index
        return "missing", LocalSpeech("There's no clipboard item {0}.".format(number))
    try:
        writer(text)
    except Exception:
        return "failed", LocalSpeech("I couldn't copy clipboard item {0}.".format(int(index)))
    if not paste:
        return "copied", LocalSpeech("Copied item {0}.".format(int(index)))
    try:
        paster()
    except Exception:
        return "paste_failed", LocalSpeech("Copied item {0}, but I couldn't paste it.".format(int(index)))
    return "pasted", LocalSpeech("Pasted item {0}.".format(int(index)))


def activate_clipboard_index(index, paste=False, writer=None, paster=None, history=None):
    """Copy item `index` back, and paste it when `paste` is true.

    Returns (status, LocalSpeech). The speech does not include the item text.
    """
    history = CLIPBOARD if history is None else history
    if writer is None:
        writer = write_general_pasteboard
    if paster is None:
        paster = paste_keystroke
    return _activate(history, index, bool(paste), writer, paster)


def copy_clipboard_from_text(text, writer=None, history=None):
    index = parse_item_index(text)
    if index is None:
        return LocalSpeech("Which clipboard item?")
    _status, speech = activate_clipboard_index(index, paste=False, writer=writer, history=history)
    return speech


def paste_clipboard_from_text(text, writer=None, paster=None, history=None):
    index = parse_item_index(text)
    if index is None:
        return LocalSpeech("Which clipboard item?")
    _status, speech = activate_clipboard_index(
        index, paste=True, writer=writer, paster=paster, history=history)
    return speech


def outbox_reply(result):
    """Words that may be written to the iPhone outbox.

    LocalSpeech stays on the Mac. Clipboard commands return LocalSpeech, so this
    is empty for them.
    """
    if isinstance(result, LocalSpeech):
        return ""
    if isinstance(result, str):
        return result
    return ""


def save_clipboard(history, path):
    """Write the items as JSON, mode 0600. Refuses an iCloud path.

    The text is not printed. The running app does not call this.
    """
    if icloud_clipboard_path(path):
        raise ValueError("clipboard history is never written to iCloud")
    directory = os.path.dirname(os.path.abspath(path))
    if directory:
        os.makedirs(directory, exist_ok=True)
    payload = json.dumps(
        {"v": 1, "items": history.texts()},
        ensure_ascii=False,
    ).encode("utf-8")
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    fd = os.open(path, flags, 0o600)
    try:
        os.write(fd, payload)
    finally:
        os.close(fd)
    os.chmod(path, 0o600)


def load_clipboard(history, path):
    """Replace items from a JSON file. A bad file leaves the history as it was."""
    if icloud_clipboard_path(path):
        raise ValueError("clipboard history is never read from iCloud")
    try:
        with open(path, encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return False
    items = data.get("items") if isinstance(data, dict) else None
    if not isinstance(items, list):
        return False
    history.replace_items(items)
    return True


def poll_once(history, reader):
    """Read once and observe. `reader` returns a Snapshot. Tests pass a fake."""
    return history.observe(reader())


def read_general_pasteboard():
    """One snapshot from the general pasteboard. Mac only. Tests do not call this."""
    from AppKit import NSPasteboard, NSWorkspace
    board = NSPasteboard.generalPasteboard()
    count = int(board.changeCount())
    raw_types = board.types() or ()
    types = tuple(str(item) for item in raw_types)
    text = board.stringForType_("public.utf8-plain-text")
    if text is None:
        text = board.stringForType_("NSStringPboardType")
    front = None
    bundle = None
    try:
        app = NSWorkspace.sharedWorkspace().frontmostApplication()
        if app is not None:
            front = app.localizedName()
            bundle = app.bundleIdentifier()
    except Exception:
        front = None
        bundle = None
    return Snapshot(
        change_count=count,
        text=None if text is None else str(text),
        types=types,
        frontmost=None if front is None else str(front),
        bundle_id=None if bundle is None else str(bundle),
    )


def write_general_pasteboard(text):
    """Put plain text back on the general pasteboard. Does not log it."""
    from AppKit import NSPasteboard
    board = NSPasteboard.generalPasteboard()
    board.clearContents()
    ok = board.setString_forType_(str(text), "public.utf8-plain-text")
    if ok is False:
        raise OSError("pasteboard write failed")


def paste_keystroke():
    """Command-V in the front app. The text is already on the pasteboard."""
    import subprocess
    subprocess.run(
        ["osascript", "-e", 'tell application "System Events" to keystroke "v" using command down'],
        check=False,
    )


def start_clipboard_thread(reader=None, history=None, interval=None):
    """Poll changeCount on a daemon thread. No socket. The default reader is AppKit."""
    global _thread
    if reader is None:
        reader = read_general_pasteboard
    if history is None:
        history = CLIPBOARD
    if interval is None:
        interval = CLIPBOARD_POLL_SECONDS

    def loop():
        while True:
            try:
                poll_once(history, reader)
            except Exception as exc:
                print(poll_error_line(exc))
            time.sleep(interval)

    with _thread_lock:
        if _thread is not None and _thread.is_alive():
            return
        _thread = threading.Thread(target=loop, name="jev-clipboard", daemon=True)
        _thread.start()
